//user reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'
// ui reducer types
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const STOP_LOADING = 'STOP_LOADING'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

//data reducer types
export const SET_PLANTS = 'SET_PLANTS'
export const SET_PLANT = 'SET_PLANT'
export const LOADING_DATA ='LOADING_DATA'
export const LIKE_PLANT = 'LIKE_PLANT'
export const UNLIKE_PLANT ='UNLIKE_PLANT'
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_USER_PLANTS = 'SET_USER_PLANTS'
export const DELETE_PLANT = 'DELETE_PLANT'
export const LOADING_PLANT_IMAGE = 'LOADING_PLANT_IMAGE'
export const POST_PLANT = 'POST_PLANT'
export const LIKE_COMMENT = 'LIKE_COMMENT'
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const POST_COMMENT = 'POST_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
